### ISSUE TITLE
[cmake] project should allow FIND_PACKAGE(gait REQUIRED) or similar

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/gait#1]
[cmake] project should allow FIND_PACKAGE(gait REQUIRED) or similar.

**Comment by jgvictores** [comment]
Check https://github.com/roboticslab-uc3m/project-generator for an example.

**Comment by munozyanez** [comment]
Done and tested in debian stretch.
Find the Find.cmake file needed in the example:
https://github.com/roboticslab-uc3m/gaitcontrol/tree/master/cmake

**Comment by munozyanez** [comment]
Closing issue for lack of comments
