### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/gait#5]
Add tests (e.g. via gtest) and continuous integration (e.g. via travis).

**Comment by munozyanez** [comment]
Lets do it!

**Comment by jgvictores** [comment]
Started off at 911083ee34d6ae9cae04a163046a3d14cbe44cbe in current branch `fix-5-travis`.

**Comment by jgvictores** [comment]
Added travis, integrated service at bb9e87891c6b1a4dae2c0056fd1fbb3fa4bf5fcf.
