### ISSUE TITLE
Fix build on travis

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/gait#6]
Fix build on travis, failing at https://travis-ci.org/roboticslab-uc3m/gait/jobs/219292051 due to lack of c++11 directive.

**Comment by jgvictores** [comment]
Note to self: export defines for https://github.com/roboticslab-uc3m/kinematics-dynamics (unless doubtful scenario where I use targets and properties are exported with more advanced cmake mechanisms than the ones I usually use).

**Comment by jgvictores** [comment]
From [this blog post](http://jsteemann.github.io/blog/2014/10/17/using-travis-ci-for-a-c-plus-plus-11-project/):
> While writing this post, Travis CI build machines run on Ubuntu 12.04 LTS 64 bit. This version of Ubuntu is rather old already, and does not bring too many packages for C++11 development. For example, the default C++ compiler installed on TravisCI is g++-4.6.3. This version doesn’t even understand the compile option -std=c++11.
Official C++11 support started in g++ 4.7, though C++0x features were supported way earlier. But to get decent C++11 support in g++, it is best to use g++4.8 or higher.

Which actually recommends:

> language: cpp
> compiler: g++
> 
> before_install:
> - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
> - sudo apt-get update -qq
> 
> install:
> - sudo apt-get install -qq g++-4.8
> - export CXX="g++-4.8"

Different ways to go here:
1. Keep on trying with `g++-4.6.3`.
1. Drop c++11 for now (I do not see use of advanced features, in fact look at [header](https://github.com/roboticslab-uc3m/gait/blob/bb9e87891c6b1a4dae2c0056fd1fbb3fa4bf5fcf/src/tools.h#L196) vs [implementation](https://github.com/roboticslab-uc3m/gait/blob/bb9e87891c6b1a4dae2c0056fd1fbb3fa4bf5fcf/src/tools.cpp#L374)).
1. Go on with `g++-4.8`.

For now I'm going with dropping the mentioned ambiguous c++11 mentioned line of (2), see if (1) or (3) is the way to go after that.

**Comment by PeterBowman** [comment]
That's quite an old post. Trusty build environment for Travis is [still in beta](https://docs.travis-ci.com/user/trusty-ci-environment/), but we've been using it at asrob-uc3m/robotDevastation since last December. As fas as I can tell, it supports g++ 4.8.4 out-of-the-box.

**Comment by jgvictores** [comment]
From my last comment and build I suspect C++11 wasn't really used in this project at all yet, but I think it's completely reasonable to move on to build on Trusty. Will do as soon as I get my hands on a PC.  😊

Thanks a lot for keeping an eye and helping out!

**Comment by jgvictores** [comment]
Ok, there were two uses of c++11:
1. `std::__cxx11::string`, which was successfully removed at 98d423a8bbf48a950ef188f59484399311273d03
1. Many `uint`, seen at https://travis-ci.org/roboticslab-uc3m/gait/jobs/219688405

I'm going to keep (1) and merge, then plan to update travis to Trusty to put some more updated gcc directives.
